defmodule CoreWeb.GraphQL.Types do
  @moduledoc false
  use CoreWeb.GraphQL, :type
  alias CoreWeb.GraphQL.Types

  import_types(Absinthe.Plug.Types)
  import_types(Absinthe.Type.Custom)
  import_types(Types.CustomTypes)
  import_types(Types.UserType)
  import_types(Types.SessionType)
  import_types(Types.LegalType)
  import_types(Types.BusinessTypeType)
  import_types(Types.BusinessType)
  import_types(Types.ServiceType)
  import_types(Types.BranchType)
  import_types(Types.RawBusinessType)
  import_types(Types.EmailTemplateType)
  import_types(Types.RegionType)
  import_types(Types.EmployeeType)
  import_types(Types.AclType)
  import_types(Types.MenuType)
  import_types(Types.DropdownType)
  import_types(Types.CalendarType)
  import_types(Types.SearchBSPType)
  import_types(Types.JobType)
  import_types(Types.SettingType)
  import_types(Types.ScheduleType)
  import_types(Types.PromotionType)
  import_types(Types.DynamicType)
  import_types(Types.OffDayType)
  import_types(Types.PaymentType)
  import_types(Types.HyperWalletPaymentType)
  import_types(Types.MetaType)
  import_types(Types.InvoiceType)
  import_types(Types.TaxType)
  import_types(Types.BidType)
  import_types(Types.GeoZoneType)
  import_types(Types.ErrorType)
  import_types(Types.LeadType)
  import_types(Types.NotificationType)
  import_types(Types.PaypalPaymentType)
  import_types(Types.CashPaymentType)
  import_types(Types.EmailSettingType)
  import_types(Types.ReferralType)
  import_types(Types.UpsertSeedsType)
  import_types(Types.CashfreePaymentType)
  import_types(Types.UserInstallsType)
  import_types(Types.ProfileType)
  import_types(Types.FileType)
  import_types(Types.JobNoteType)
  import_types(Types.BspEmailTemplate)
  import_types(Types.ProductWarrantyType)
  import_types(Types.TudoChargesType)
  import_types(Types.ProductType)
  import_types(Types.OrderType)
  import_types(Types.WarehouseType)
  import_types(Types.InventoryType)
end
